export const words = [
    'home',
    'machiaj',
    'unghii',
    'păr',
    'price list',
    'coafat',
    'contact',
    'facebook',
    'instagram',
    'despre noi',
    'noutăți',
    'misiunea',
    'viziunea',
    'povestea noastră',
    'machaij mireasă',
    'salon',
    'Denisa',
    'Mădălina',
    'program',
    'informații de contact',
]